### ISSUE TITLE
我把Mp4文件作为背景，黑屏了。。

### ISSUE THREAD

**Issue by liaobinbin** [WuSiYu/PlasmaVideoWallpaper#1]
背景全黑。
系统gentoo + plasma 5.9.3

**Comment by ivanslifer12** [comment]
Hey
its works great the only problem it flicks black screen for a sec after the video ends.
runnig x86_64 Linux 4.10.9-1-ARCH

**Comment by liaobinbin** [comment]
我补充一句，实际上在系统提示里面有报错，提示我没有合适的解码器，装了在全局
USE添加了mp4 ffmpeg后，更新了了一下系统依赖。重启后，视频桌面恢复了。

**Comment by arklee** [comment]
原来如此，，，黑屏是因为没有解码器
