### ISSUE TITLE
视频加载时间太长

### ISSUE THREAD

**Issue by Mecry-git** [WuSiYu/PlasmaVideoWallpaper#11]
刚开始我还以为是不能循环了呢。。。结果等了大半天才开始第二遍。。。是什么原因呢？视频是mp4，才30多mb啊？咋回事呢？

**Comment by WuSiYu** [comment]
尝试打开“防止循环时的黑屏卡顿”选项

**Comment by Mecry-git** [comment]
搞panon的widget时下载了它所有的依赖，突然就好了。。。反正已经解决了，可能是奇奇怪怪的包缺失吧
