### ISSUE TITLE
能否将这个项目打包到 AUR 或者 Arch Linux CN 源？

### ISSUE THREAD

**Issue by OriginCode** [WuSiYu/PlasmaVideoWallpaper#4]
很期待这个项目能够被收录至AUR

**Comment by BruceZhang1993** [comment]
@OriginCode 前排膜拜打包者

**Comment by mokurin000** [comment]
这个项目竟然没有License文件…… 似乎作者也不关注了

**Comment by OriginCode** [comment]
@poly000 挖坟可还行……close 了 close 了（

**Comment by mokurin000** [comment]
> @poly000 挖坟可还行……close 了 close 了（

包打了吗（

**Comment by OriginCode** [comment]
@poly000 没打啊（

**Comment by mokurin000** [comment]
> @poly000 没打啊（

（催更

**Comment by OriginCode** [comment]
@poly000 沒 License 我打啥啊（

**Comment by mokurin000** [comment]
> @poly000 沒 License 我打啥啊（

写PKGBUILD（

**Comment by OriginCode** [comment]
@poly000 自己寫去（

**Comment by mokurin000** [comment]
> @poly000 自己寫去（

我连/usr/share都不认识的

**Comment by mokurin000** [comment]
> @poly000 自己寫去（

<del>话说这是对KDE4写的插件？ KDE5能用吗</del>

**Comment by OriginCode** [comment]
> > @poly000 自己寫去（
> 
> 话说这是对KDE4写的插件？ KDE5能用吗

你看看 README，还 KDE 4……

**Comment by mokurin000** [comment]
> > > @poly000 自己寫去（
> > 
> > 
> > 话说这是对KDE4写的插件？ KDE5能用吗
> 
> 你看看 README，还 KDE 4……

目害了（

**Comment by WuSiYu** [comment]
LICENSE 已添加
AUR记得之前已经有人打过包了，似乎还不止一个（plasmavideowallpaper-git、better-plasma5-video-wallpaper-git）
