### ISSUE TITLE
tearing issue

### ISSUE THREAD

**Issue by hashalon** [WuSiYu/PlasmaVideoWallpaper#5]
On a fast moving video, I noticed that I had a lot of tearing. Which is quite ugly...
I am wondering if there is a way to fix this.
Either there is an option to add to this plugin or maybe the problem comes from KDE itself.
I would be glad if I could have your feedback on this.

**Comment by WuSiYu** [comment]
I have the same issue on my desktop PC, and I think it is a issue of KDE or the video card driver.
My desktop PC has a NVIDIA video card, and it will tearing even I am playing a video on a normal video player application.
This plugin using the QML's MediaPlayer type to play the video, which is a very simple video player and I think it itself can't do anything about the tearing issue.
I am still trying to find a solution to fix it, but the solution may varies with hardware and drivers.
At now, you can try to change the vsync option of KDE or your video card drivers, it may have some effect.
