### ISSUE TITLE
i3wm

### ISSUE THREAD

**Issue by jorhelp** [WuSiYu/PlasmaVideoWallpaper#9]
It seems not support i3-wm environment...

**Comment by WuSiYu** [comment]
Yes, it doesn't support other DE or WM. This plugin is based on QML and some components of the KDE Plasma desktop, it is designed for integrated with KDE Plasma desktop, so only works on KDE Plasma desktop.

You can found other kind of wallpaper software which not integrated with an specific DE or WM, it may works for you.
